### ISSUE TITLE
See more for customers too

### ISSUE THREAD

**Issue by Alex-Yates** [cthulhucreates/dlmconsultants#34]
I understand the concern about many clients.

Perhaps better if we just list three by default, but have a "see more" button, like with testimonials.

Then, under see more, we can add the full list. The more the better.

**Comment by Alex-Yates** [comment]
Probaby top 3 are United Nations, NHS and Redgate, followed by FCMA, Greentube and Megadata and then the others.

(MegaData are actually not that well known but they sound impressive and they have "Health Systems" in the logo. :-)

**Comment by ZoeLocke** [comment]
Closing as already exists under issue 11
