### ISSUE TITLE
Consider reducing testimonials

### ISSUE THREAD

**Issue by OzLocke** [cthulhucreates/dlmconsultants#7]
There are a lot of testimonials, which is great, but one of the ways this site reduces load is by not using carousels. As a result, the testimonials section is pretty big. 

I see two options here: reduce the number of testimonials, or prune the testimonial text (which could lead to "out of context" issues, with people not being quoted in full)

**Comment by Alex-Yates** [comment]
Is it possible to include two or three of the best ones with a link to the others?

I think having the really long list is really impressive so I want to keep that somewhere, but I see the point about putting a shorter list front and centre. And I agree, carousels are pretty much the devil.

**Comment by OzLocke** [comment]
No worries, I may be able to lean on the functionality I'm using elsewhere, so we can have a "see even MORE testimonials" button at the bottom of the list

**Comment by OzLocke** [comment]
I've reduced them to 6 for now, and will look at adding the ability to view more when redoing the structure
